nameOverride: ""
fullnameOverride: ""
partOf: ""
component: ""

replicaCount: 1

job:
  enabled: false
  annotations: {}
  backoffLimit: 3
  restartPolicy: OnFailure

image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

command: []
args: []

ports:
  - name: http
    containerPort: 8080
    protocol: TCP

env: {}
envFrom: []

configMap:
  enabled: false
  envFrom: true
  data: {}

secret:
  enabled: false
  type: Opaque
  stringData: {}

service:
  enabled: true
  type: ClusterIP
  annotations: {}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts: []
  tls: []

resources: {}

livenessProbe: {}
readinessProbe: {}
startupProbe: {}

persistence:
  enabled: false
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  storageClassName: ""
  annotations: {}

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}
