apiVersion: v2
name: foundation
description: Foundation deployment chart
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgres
    version: 0.1.0
    repository: file://../postgres/deployment
  - name: liquibase
    version: 0.1.1
    repository: file://../liquibase/deployment
