packages:
  - "user-management/frontend/app/*"
  - "product-management/frontend/app/*"
  - "order-management/frontend/app/*"
  - "online-storefront/frontend/app/*"
  - "shared-components/frontend/package/*"
  - "shared-components/frontend/package/design-system/ds/*"
  - "shared-components/frontend/app/*"

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  lmdb: true
  msgpackr-extract: true

catalog:
  "@angular/common": "^21.2.17"
  "@angular/compiler": "^21.2.17"
  "@angular/core": "^21.2.17"
  "@angular/forms": "^21.2.17"
  "@angular/platform-browser": "^21.2.17"
  "@angular/router": "^21.2.17"
  "rxjs": "~7.8.0"
  "tslib": "^2.3.0"
  "ng-packagr": "^21.2.0"
  "@angular-devkit/architect": "^0.2102.0"
  "@angular-devkit/build-angular": "^21.2.0"
  "@angular-devkit/core": "^21.2.0"
  "@angular/compiler-cli": "^21.2.17"
  "@angular/platform-browser-dynamic": "^21.2.17"
  "@angular/build": "^21.2.10"
  "@angular/cli": "^21.2.10"
  "@storybook/addon-a11y": "^10.3.6"
  "@storybook/addon-docs": "^10.3.6"
  "@storybook/addon-onboarding": "^10.3.6"
  "@storybook/angular": "^10.3.6"
  "@storybook/test": "^8.6.15"
  "@types/node": "^25.6.2"
  "jsdom": "^28.0.0"
  "prettier": "^3.8.1"
  "storybook": "^10.3.6"
  "typescript": "~5.9.2"
  "vitest": "^4.1.9"
  "style-dictionary": "^5.4.1"
