app:
  nameOverride: liquibase
  fullnameOverride: liquibase
  partOf: foundation
  component: migration
  replicaCount: 1
  deployment:
    enabled: false
  job:
    enabled: true
    annotations:
      helm.sh/hook: post-install,post-upgrade
      helm.sh/hook-delete-policy: before-hook-creation
    backoffLimit: 6
    restartPolicy: OnFailure
  image:
    repository: eco-test/liquibase
    tag: latest
    pullPolicy: IfNotPresent
  ports: []
  service:
    enabled: false
  env:
    LIQUIBASE_COMMAND_URL: jdbc:postgresql://postgres:5432/ecoDB
    LIQUIBASE_COMMAND_USERNAME: liquibase
  secret:
    enabled: true
    stringData:
      LIQUIBASE_COMMAND_PASSWORD: change-me
  resources: {}
