app:
  nameOverride: liquibase
  fullnameOverride: liquibase
  partOf: foundation
  component: migration
  replicaCount: 1
  image:
    repository: eco-system/liquibase
    tag: latest
    pullPolicy: IfNotPresent
  ports: []
  service:
    enabled: false
  env:
    LIQUIBASE_COMMAND_URL: jdbc:postgresql://postgres:5432/ecoDB
    LIQUIBASE_COMMAND_USERNAME: liquibase
  secret:
    enabled: true
    stringData:
      LIQUIBASE_COMMAND_PASSWORD: change-me
  resources: {}
