driver: org.postgresql.Driver
changeLogFile: master_changelog.xml

liquibase.hub.mode: all

username=liquibase
password=${LIQUIBASE_PASSWORD}
searchPath=/liquibase/,/liquibase/scripts/,/liquibase/changelogs/
url=jdbc:postgresql://db:5432/ecoDB