storefront-gateway: {}
storefront-web-app: {}

storefrontWebAppApiIngress:
  enabled: false
  className: ""
  annotations: {}
  host: ""
  path: /api
  pathType: Prefix
  serviceName: storefront-gateway
  servicePortName: http
  tls: []
