cart-gateway: {}
storefront-gateway: {}
storefront-web-app: {}

cartGatewayApiIngress:
  enabled: false
  className: ""
  annotations: {}
  host: ""
  path: /api/cart
  pathType: Prefix
  serviceName: storefront-cart-gateway
  servicePortName: http
  tls: []

storefrontWebAppApiIngress:
  enabled: false
  className: ""
  annotations: {}
  host: ""
  path: /api
  pathType: Prefix
  serviceName: storefront-gateway
  servicePortName: http
  tls: []
