app:
  nameOverride: user-gateway
  fullnameOverride: user-gateway
  partOf: user-management
  component: backend
  image:
    repository: eco-system/user-gateway
    tag: latest
    pullPolicy: IfNotPresent
  ports:
    - name: http
      containerPort: 8080
      protocol: TCP
  service:
    enabled: true
    ports:
      - name: http
        port: 8080
        targetPort: http
        protocol: TCP
  env:
    PORT: "8080"
    USER_SERVICE_URL: http://user-service:8080
  readinessProbe:
    tcpSocket:
      port: http
    initialDelaySeconds: 10
    periodSeconds: 10
