apiVersion: v2
name: minio
description: Foundation S3-compatible object storage deployment
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: app
    version: 0.1.0
    repository: file://../../../deployment/charts/app
