user-service: {}
user-gateway: {}
admin-web-app: {}

adminWebAppApiIngress:
  enabled: false
  className: ""
  annotations: {}
  host: ""
  path: /api
  pathType: Prefix
  serviceName: user-gateway
  servicePortName: http
  paths: []
  tls: []

adminWebAppStoriesIngress:
  enabled: false
  className: ""
  annotations: {}
  host: ""
  path: /stories/admin-web-app
  pathType: Prefix
  serviceName: user-admin-web-app
  servicePortName: http
  tls: []
