apiVersion: v2
name: postgres
description: Foundation PostgreSQL deployment
type: application
version: 0.1.0
appVersion: "15"
dependencies:
  - name: app
    version: 0.1.0
    repository: file://../../../deployment/charts/app
