apiVersion: v2
name: shared-components
description: Shared components deployment chart
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: storybook
    version: 0.1.0
    repository: file://../frontend/app/storybook/deployment
