name: Deploy

on:
  workflow_dispatch:
    inputs:
      layer:
        description: Layer to deploy
        required: true
        default: all
        type: choice
        options:
          - all
          - ci-cd
          - foundation
          - application
      namespace:
        description: Application namespace
        required: false
        default: eco-test
      environment_file:
        description: Environment config file under config/
        required: true
        default: hp-prodesk-homelab.txt
      unchanged_application_image_tag:
        description: Image tag to use for unchanged application use-cases
        required: true
        default: latest

permissions:
  contents: read
  issues: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy-core.yml
    with:
      deployment_mode: standard
      layer: ${{ inputs.layer }}
      namespace: ${{ inputs.namespace }}
      environment_file: ${{ inputs.environment_file }}
      application_deploy_scope: all
      unchanged_application_image_tag: ${{ inputs.unchanged_application_image_tag }}
      base_ref: main
    secrets: inherit
